[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*'"

[[services]]
name = "buildrs-api"

[nixpacks.variables]
NIXPACKS_PYTHON_VERSION = "3.11" 